AuthReg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from AuthReg.views import login
app_name = "AuthReg"

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', views.registration, name="registration"),
    path('check/', views.auth_check, name='auth_check'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_profile/forma_otpravki/', views.Zayavka, name='zayavka'),
    path('BabyBuild/admin_panel/', views.admins_panel, name='ADMIN_panel'),
    path('deleteTovar/<int:id>', views.deleteTovar, name='deleteTovar'),
    path('Admin_Panel/Add_tovar', views.Add_Tovars, name='add_tovars'),
    path('deleteZayvka/<int:id>', views.deleteZayavka, name='deleteZayavka'),
    path('AcceptZayvka/<int:id>', views.AcceptZayavka, name='AcceptZayavka')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebDes/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from WebDes import views
urlpatterns = [
        path('', views.index, name="index"),
    path('sad@123/', include('AuthReg.urls', namespace='AuthReg')),
    path('catalogue', views.katalog, name="katalog")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('WebDes.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Add_Tovar.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% if request.user.is_staff %}
        <p>Welcome {{ user.username }} </p>

<form enctype="multipart/form-data" action="{% url 'AuthReg:add_tovars' %} "  method="POST">
  {% csrf_token %}
    {{ form.as_p }}
<button type="submit">Добавить</button>
</form>
    <a href="{% url "AuthReg:ADMIN_panel" %}"><h2>back</h2></a>
{% endif %}
</body>
</html>

templates/admin.html
{% load static %}
<html lang="ru">
<head>
	<meta charset="utf-8" />
	<title>Админ-панель</title>
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    <link rel="stylesheet" href="{% static "style/admin.css" %}">
</head>

<body>
{% if request.user.is_staff %}
<div class="table-title">
<h3>Админ панель</h3>
    <a href="{% url "AuthReg:user_profile" %}"><h3>Профиль</h3></a>
</div>
<table class="table-fill">
<thead>
<tr>
    <th class="text-left" >ФИО клиента</th>
    <th class="text-left">Номер телефона</th>
    <th class="text-left">Почта</th>
    <th class="text-left">Тип работы</th>
    <th class="text-left">дата</th>
    <th class="text-left">Цена</th>
    <th class="text-left">Комментарий</th>
    <th class="text-left"></th>
    <th class="text-left"></th>
</tr>
</thead>
<tbody class="table-hover">
{% for el in zayavki %}
<tr>
    <td data-th="FIO">{{ el.first_name }} {{ el.last_name }}</td>
    <td data-th="phone">{{ el.phone }}</td>
    <td data-th="email">{{ el.email }}</td>
    <td data-th="type">{{ el.work_type }}</td>
    <td data-th="data">12.11.23</td>
    <td data-th="price">$460,935,665</td>
    <td data-th="comment">ХОЧУ КАЛЬЯННУЮ</td>
    <form action="{% url 'AuthReg:AcceptZayavka' el.pk %}" method="POST">
  {% csrf_token %}
    <th class="del"><button type="submit" name="{{ el.id }}">Принять</button></th>
        </form>
    <form action="{% url 'AuthReg:deleteZayavka' el.pk %}" method="POST">
  {% csrf_token %}
    <th class="del"><button type="submit" name="{{ el.id }}">Удалить</button></th>
        </form>
{% endfor %}


</tbody>
</table>
<a href="{% url "katalog" %}"><h3>Каталог</h3></a>
<a href="{% url "AuthReg:add_tovars" %}"><h3>Добавить товар</h3></a>
    <table class="table-fill">
    <thead>
    <tr>
        <th class="text-left" >Название</th>
    <th class="text-left">Площадь</th>
    <th class="text-left">Фото</th>
        <th class="text-left">Цена</th>
        <th class="text-left"></th>
    <th class="text-left"></th>
    </tr>
    </thead>
    <tbody class="table-hover">
    {% for el in tovari %}
<tr>
    <td data-th="name">{{ el.name }}</td>
    <td data-th="ploshad">{{ el.ploshad }}</td>
    <td data-th="image">{{ el.image }}</td>
    <td data-th="cost">{{ el.cost }}</td>
        <form action="{% url 'AuthReg:deleteTovar' el.pk %}" method="POST">
  {% csrf_token %}
    <th class="del"><button type="submit" name="{{ el.id }}">Delete</button></th>
        </form>

{% endfor %}
</table>
    {% else %}
    <p>Fuck off</p>
{% endif %}


  </body>

templates/auto.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="{% static '/style/auto.css' %}">
    <title>Art Life</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
    <main>
        <div class="content">
            <div class="menu_auto">
                <form action="{% url 'AuthReg:login' %}" method="POST">
                        {% csrf_token %}
                    <div class="form">
                        <input type="text" placeholder="Юзер" class="form-control py4" name="username">
                    <input type="email" placeholder="Почта" class="form-control py4" name="email">
                    <input type="password" placeholder="Пароль" class="form-control py4" name="password">


                 <button>Войти </button>
                        <a href="{% url 'AuthReg:registration' %}">Регистрация</a>
                    </div>
            </form>

            </div>
        </div>


        

    </main>
    <footer>
        <p> Лабораторная работа</p>
        <p> Иванов Владислав и Соловьёв Дмитрий</p>
        <p> ИСП/Р-22-11</p>
    </footer>

    
</body>
</html> 

templates/forma.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static '/style/forma.css' %}" rel="stylesheet" />
    <title>Заявка Art Life</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
    <main>
        <div class="space">
        </div>
        <div class="container">
            <div class="block_form">
                <h1> Заполните форму и мы с вами свяжемся</h1>
                <form action="{% url 'AuthReg:zayavka' %}" method="POST">
                        {% csrf_token %}
                    <input placeholder="Имя"  type="text" class="form-control py4" name="first_name"><br><br>
                    <input placeholder="Фамилия" type="text" class="form-control py4" name="last_name"><br><br>
                    <input placeholder="Почта"  type="email" class="form-control py4" name="email"><br><br>
                    <input placeholder="Номер телефона"  type=" number" class="form-control py4" name="phone"><br><br>
                    <input type="checkbox" class="form-control py4" name="ur_lico">
                    <label for="checkbox">Юридическое лицо</label><br><br>
                    {{ form.work_type }}
                    <button type="submit"> Отправить </button>
                </form>
            </div>
        </div>
    </main>
    
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static '/style/main.css' %}" rel="stylesheet" />
    <title>Art life</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
    <main>
        <section class="first_sect">
            <div class="container">
                <h1> Art Life - Строительная компания</h1>
                <h1>Мы создаем неповторимые архитектурные<br>
                    шедевры, сочетая искусство и строительство</h1>
            </div>
        </section>
        <div class="vstavka"></div>
        <section class="second_sect">
            <h1 class="uslugH1"> Наши услуги</h1>
            <div class="cont">
                <div class="block_uslug">
                    <h2> Дизайн</h2>
                    <p> Создаем уникальный и
                        эстетичный дизайн </p>
                </div>
                <div class="block_uslug">
                    <h2> Строительство</h2>
                    <p> Проффессиональная
                        команда  строителей </p>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <p> Лабораторная работа</p>
        <p> Иванов Владислав и Соловьёв Дмитрий</p>
        <p> ИСП/Р-22-11</p>

    </footer>
    
</body>
</html>

templates/katalog.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static '/style/katalog.css' %}" rel="stylesheet" />
    <title>Каталог</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
    <main>
        <div class="container">
            <h1 id="katalog_Heading"> Наш Каталог</h1>

            <div class="line_block">
            {% for el in tovari %}
                <div class="block">


                    <h2> {{ el.name }} </h2>
                    <img src="{{ el.image }}" alt="картинка" width="382" height="193">
                    <p> {{ el.ploshad }}  {{ el.cost }}</p>
                    <button><a id="btn_block"  href="{% url 'AuthReg:auth_check' %}">Купить</a></button>

                </div>
                {% endfor %}


    
            </div>

        </div>
    </main>
    <footer>
        <p> Лабораторная работа</p>
        <p> Иванов Владислав и Соловьёв Дмитрий</p>
        <p> ИСП/Р-22-11</p>

    </footer>

        
</body>
</html>

templates/reg.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static '/style/reg.css' %}" rel="stylesheet" />
    <title>Art Life</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
<main>
        <div class="content">
            <div class="menu_reg">
                <form action="{% url 'AuthReg:registration' %}" method="POST">
                        {% csrf_token %}
                <div class="line">
                    <div class="form">
                        <input placeholder="Имя"  type="text" class="form-control py4" name="first_name">
                        <input placeholder="Фамилия" type="text" class="form-control py4" name="last_name">
                    </div>
                </div>
                <div class="line">
                        <div class="form">
                            <input placeholder="Почта"  type="email" class="form-control py4" name="email">
                            <input placeholder="Номер телефона"  type="number" class="form-control py4" name="phone">

                        </div>
                </div>
                <div class="line">
                    <div class="form">
                        <input type="password" placeholder="Пароль" class="form-control py4" name="password1">
                        <input type="password" placeholder="Пароль еще раз" class="form-control py4" name="password2">

                    </div>
                </div>
                <div class="line">
                    <input placeholder="Username"  type="text" class="form-control py4" name="username">
                    <<button>Регистрация</button>>
                </div>
                </form>
            </div>
        </div>



    </main>
    <footer>
        <p> Лабораторная работа</p>
        <p> Иванов Владислав и Соловьёв Дмитрий</p>
        <p> ИСП/Р-22-11</p>
    </footer>

    
</body>
</html>

templates/send_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/user_cabinet.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link type="text/css" href="{% static '/style/components.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static '/style/user_cabinet.css' %}" rel="stylesheet" />
    <title>Art Life</title>
</head>
<body>
    <header>
            <h1>Art Life</h1>
            <nav>
                <a href="{% url 'katalog' %}" class="nav_item">Каталог</a>
                <a href="{% url 'index' %}" class="nav_item">Главная</a>
                <a href="#" class="nav_item">Контакты</a>
            </nav>
            <a href="{% url "AuthReg:auth_check" %}"><img src="{% static "img/icon_aut.png" %}" alt="Регистрация"></a>
    </header>
    <main>
        <div class="container">
            <div class="info_profil">
                <h2>Ваши данные</h2>
                <p> {{ user.first_name }} {{ user.last_name }} </p>
                <p> {{ user.email }}</p>
                <p> {{ user.phone }}</p>
            </div>
            <div class="vstavka"> </div>
            <div class="zakaz">
                <h3><a href="{% url 'AuthReg:zayavka' %}">Отправить заявку</a></h3>
                <h2> Ваши заказы</h2>

                <table>
                    <tr><th>Тип работ</th> <th> Цена</th><th>Комментарий</th><th> Статус</th></tr>
                    <tr> <th> Ремонт</th> <th> 5200</th><th> Чтобы не было слышно соседней</th><th> В процессе</th></tr>

                </table>



                
            </div>

        </div>

    </main>
    <footer>
        <p> Лабораторная работа</p>
        <p> Иванов Владислав и Соловьёв Дмитрий</p>
        <p> ИСП/Р-22-11</p>
    </footer>
    
</body>
</html>